### PR TITLE
Doc examples

### PR DESCRIPTION
**Pull request by EssamWisam**
@ablaom could you review the docs as found in the notebooks in the examples folder. These autogenerate markdown in the docs folder.

### CODE REVIEW

**Comment by ablaom** [comment]
I've reviewed using ReviewNB. Just waiting on your responses.

**Comment by EssamWisam** [comment]
Here is a small issue. For an unknown reason and to my surprise my `.gitignore` in this branch had `examples/*ipynb` which is why the walkthrough and other doc example notebooks where not uploaded. I cannot find them locally either.

The remedy is as follows. If you want to regenerate the notebooks, all the info is in the markdown files which are up in the docs folder and I may just use Literate whatsoever. Thus, I will be okay with applying your suggestions to the markdown files.

**Comment by ablaom** [comment]
But I already reviewed these examples. Are you not able to access my comments now? If not, that's not too big a deal. Basically, if I recall, the important points were: 

-  To ensure notebooks can be run in the future, even after breaking changes to the code base, give the examples their own environment (i.e., add a Project.toml *and* Manifest.toml) and beginning each notebook with something like

```julia
# The following code loads a Julia package environment known to work with this notebook for all Julia versions > 1.9.
# The notebook must have the relevant `Project.toml` and `Manifest.toml` files in the same directory as the notebook.
using Pkg
Pkg.activate(@__DIR__)
Pkg.instantiate()
```

- In your plots, it's difficult to understand the comparisons. It would help if you used a different marker (e.g., cross) to label the oversampled points.

- Before your `include("utils.jl")` line, add a comment saying what this file includes (eg. "provides  `plot_comparison` method).

**Comment by EssamWisam** [comment]
I wasn't referring to the "simple examples" notebooks. These are still intact and I could see your review on `ReviewNB`. I was talking about the walkthrough and doc examples notebooks which show up in the docs
image
These notebooks are lost but their markdown (which is what's rendered in the docs) is in `docs/src/examples` thankfully are not.

This is just to clarify; I believe you're done reviewing these.

**Pull request merged**
